# Generated by Django 6.0.6 on 2026-06-25 10:20

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('groups_app', '0003_group_monthly_fee'),
        ('students', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('payment_date', models.DateField()),
                ('method', models.CharField(choices=[('CASH', 'Naqd'), ('CARD', 'Karta'), ('TRANSFER', "O'tkazma")], default='CASH', max_length=20)),
                ('note', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='created_payments', to=settings.AUTH_USER_MODEL)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payments', to='groups_app.group')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payments', to='students.student')),
            ],
            options={
                'verbose_name': "To'lov",
                'verbose_name_plural': "To'lovlar",
                'ordering': ('-payment_date', '-created_at'),
            },
        ),
        migrations.CreateModel(
            name='StudentMonthBalance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.DateField()),
                ('required_amount', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('paid_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('status', models.CharField(choices=[('OPEN', 'Ochiq'), ('PARTIAL', 'Qisman'), ('CLOSED', 'Yopildi')], default='OPEN', max_length=20)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='student_month_balances', to='groups_app.group')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='month_balances', to='students.student')),
            ],
            options={
                'verbose_name': 'Oylik balans',
                'verbose_name_plural': 'Oylik balanslar',
                'ordering': ('student__last_name', 'student__first_name', 'month'),
                'unique_together': {('student', 'group', 'month')},
            },
        ),
        migrations.CreateModel(
            name='PaymentAllocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('payment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='allocations', to='payments.paymenttransaction')),
                ('balance', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payment_allocations', to='payments.studentmonthbalance')),
            ],
            options={
                'verbose_name': "To'lov taqsimoti",
                'verbose_name_plural': "To'lov taqsimotlari",
                'ordering': ('balance__month',),
            },
        ),
    ]
