# Generated by Django 6.0.6 on 2026-09-24 21:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups_app', '0008_groupstudent_billing_dates'),
        ('payments', '0002_alter_paymentallocation_amount_and_more'),
        ('students', '0006_student_discount_type_student_discount_value_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentmonthbalance',
            name='due_date',
            field=models.DateField(blank=True, db_index=True, null=True),
        ),
        migrations.CreateModel(
            name='BillingPause',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('reason', models.CharField(blank=True, max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='billing_pauses', to='groups_app.group')),
                ('student', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='billing_pauses', to='students.student')),
            ],
            options={
                'verbose_name': "To'lov pauzasi",
                'verbose_name_plural': "To'lov pauzalari",
                'ordering': ('-start_date',),
            },
        ),
    ]
