# Generated by Django 6.0.8 on 2026-10-02 13:27

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups_app', '0008_groupstudent_billing_dates'),
        ('payments', '0005_paymenttransaction_idempotency_key'),
        ('students', '0006_student_discount_type_student_discount_value_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='paymenttransaction',
            index=models.Index(fields=['payment_date'], name='pay_date_idx'),
        ),
        migrations.AddIndex(
            model_name='paymenttransaction',
            index=models.Index(fields=['student', 'group'], name='pay_student_group_idx'),
        ),
    ]
