# Generated by Django 5.1.1 on 2026-06-29 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0002_add_parent_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='gender',
            field=models.CharField(choices=[('MALE', 'Erkak'), ('FEMALE', 'Ayol')], default='MALE', max_length=10, verbose_name='Jinsi'),
        ),
        migrations.AddField(
            model_name='student',
            name='secondary_phone',
            field=models.CharField(blank=True, max_length=20, verbose_name="Qo'shimcha telefon"),
        ),
        migrations.AddField(
            model_name='student',
            name='status',
            field=models.CharField(choices=[('ACTIVE', 'Faol'), ('FROZEN', 'Muzlatilgan'), ('LEFT', 'Ketgan')], default='ACTIVE', max_length=20, verbose_name='Holati'),
        ),
    ]
