# Generated by Django 5.1.1 on 2026-07-06 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0005_parent_student_parent'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='discount_type',
            field=models.CharField(blank=True, choices=[('PERCENTAGE', 'Foiz (%)'), ('FIXED', "Summa (so'm)")], default='PERCENTAGE', max_length=20, verbose_name='Chegirma turi'),
        ),
        migrations.AddField(
            model_name='student',
            name='discount_value',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Chegirma qiymati'),
        ),
        migrations.AddField(
            model_name='student',
            name='has_discount',
            field=models.BooleanField(default=False, verbose_name='Chegirmasi bormi'),
        ),
    ]
