# Generated by Django 6.0.6 on 2026-06-25 10:13

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('groups_app', '0002_initial'),
        ('students', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GradeSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Dars bahosi', max_length=150)),
                ('date', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='grade_sessions', to='groups_app.group')),
                ('teacher', models.ForeignKey(limit_choices_to={'role': 'TEACHER'}, on_delete=django.db.models.deletion.PROTECT, related_name='grade_sessions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Baho',
                'verbose_name_plural': 'Baholar',
                'ordering': ('-date', 'group__name', 'title'),
                'unique_together': {('group', 'date', 'title')},
            },
        ),
        migrations.CreateModel(
            name='GradeRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('percentage', models.DecimalField(decimal_places=2, max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0')), django.core.validators.MaxValueValidator(Decimal('100'))])),
                ('comment', models.CharField(blank=True, max_length=255)),
                ('graded_at', models.DateTimeField(auto_now=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='grade_records', to='students.student')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='records', to='grades.gradesession')),
            ],
            options={
                'verbose_name': 'Baho yozuvi',
                'verbose_name_plural': 'Baho yozuvlari',
                'ordering': ('student__last_name', 'student__first_name'),
                'unique_together': {('session', 'student')},
            },
        ),
    ]
