# Generated by Django 6.0.6 on 2026-06-25 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups_app', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='monthly_fee',
            field=models.DecimalField(decimal_places=2, default=500000, max_digits=12),
        ),
    ]
