# Generated by Django 5.1.1 on 2026-06-26 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups_app', '0004_alter_group_monthly_fee'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='is_paused',
            field=models.BooleanField(default=False, verbose_name="Vaqtincha to'xtatilgan"),
        ),
        migrations.AddField(
            model_name='group',
            name='lesson_days',
            field=models.CharField(blank=True, max_length=100, verbose_name='Dars kunlari'),
        ),
        migrations.AddField(
            model_name='group',
            name='lesson_time',
            field=models.TimeField(blank=True, null=True, verbose_name='Dars vaqti'),
        ),
        migrations.AddField(
            model_name='group',
            name='room',
            field=models.IntegerField(blank=True, choices=[(1, '1-xona'), (2, '2-xona'), (3, '3-xona'), (4, '4-xona'), (5, '5-xona'), (6, '6-xona')], null=True, verbose_name='Xona'),
        ),
    ]
