# Generated by Django 5.1.1 on 2026-06-26 16:15

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups_app', '0005_add_lesson_fields_and_room'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Faol'),
        ),
        migrations.AlterField(
            model_name='group',
            name='monthly_fee',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name="Oylik to'lov"),
        ),
        migrations.AlterField(
            model_name='group',
            name='start_date',
            field=models.DateField(blank=True, null=True, verbose_name='Boshlanish sanasi'),
        ),
        migrations.AlterField(
            model_name='group',
            name='teacher',
            field=models.ForeignKey(blank=True, limit_choices_to={'role': 'TEACHER'}, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='teaching_groups', to=settings.AUTH_USER_MODEL, verbose_name="O'qituvchi"),
        ),
    ]
