# Generated by Django 5.1.1 on 2026-06-30 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups_app', '0006_alter_group_is_active_alter_group_monthly_fee_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='duration',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True, verbose_name='Davomiyligi (soat)'),
        ),
        migrations.AddField(
            model_name='group',
            name='end_time',
            field=models.TimeField(blank=True, null=True, verbose_name='Tugash vaqti'),
        ),
    ]
