# Generated by Django 6.0.6 on 2026-09-24 21:24

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups_app', '0007_group_duration_group_end_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='groupstudent',
            name='left_at',
            field=models.DateField(blank=True, null=True, verbose_name='Chiqqan sana'),
        ),
        migrations.AlterField(
            model_name='groupstudent',
            name='joined_at',
            field=models.DateField(default=django.utils.timezone.localdate, verbose_name="Qo'shilgan sana"),
        ),
    ]
