# Generated by Django 5.1.1 on 2026-06-29 19:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='telegramappeal',
            name='sender_type',
            field=models.CharField(choices=[('STUDENT', "O'quvchi"), ('ADMIN', 'Admin'), ('TEACHER', "O'qituvchi")], default='STUDENT', max_length=20, verbose_name='Xabar turi'),
        ),
        migrations.AddField(
            model_name='telegramuser',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='telegram_users', to=settings.AUTH_USER_MODEL, verbose_name="Admin/O'qituvchi"),
        ),
    ]
