# Generated by Django 5.1.1 on 2026-06-29 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0002_telegramappeal_sender_type_telegramuser_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='telegramappeal',
            name='recipient_type',
            field=models.CharField(blank=True, choices=[('STUDENT', "O'quvchi"), ('ADMIN', 'Admin'), ('TEACHER', "O'qituvchi")], max_length=20, verbose_name='Kimga yuborildi'),
        ),
    ]
