# Generated by Django 5.1.1 on 2026-06-30 11:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0003_telegramappeal_recipient_type'),
        ('students', '0003_student_gender_student_secondary_phone_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TeacherMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('status', models.CharField(choices=[('SENT', 'Yuborildi'), ('FAILED', 'Xatolik')], default='SENT', max_length=10)),
                ('sent_at', models.DateTimeField(auto_now_add=True)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='received_teacher_messages', to='bot.telegramuser')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='teacher_messages', to='students.student')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='teacher_messages', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': "O'qituvchi xabari",
                'verbose_name_plural': "O'qituvchi xabarlar",
                'ordering': ('-sent_at',),
            },
        ),
    ]
