# Generated by Django 6.0.6 on 2026-07-06 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0004_teachermessage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='telegramuser',
            name='state',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
