# Generated by Django 5.1.1 on 2026-07-21 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0005_alter_telegramuser_state'),
    ]

    operations = [
        migrations.AddField(
            model_name='telegramuser',
            name='is_blocked',
            field=models.BooleanField(default=False, verbose_name='Botni blocklagan'),
        ),
    ]
