# Generated by Django 5.1.1 on 2026-07-21 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0006_telegramuser_is_blocked'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='telegramappeal',
            name='recipient_type',
        ),
        migrations.RemoveField(
            model_name='telegramuser',
            name='user',
        ),
        migrations.AlterField(
            model_name='telegramappeal',
            name='sender_type',
            field=models.CharField(choices=[('STUDENT', "O'quvchi")], default='STUDENT', max_length=20, verbose_name='Xabar turi'),
        ),
        migrations.DeleteModel(
            name='TeacherMessage',
        ),
    ]
