# Generated by Django 5.1.1 on 2026-07-21 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0007_remove_telegramappeal_recipient_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='telegramappeal',
            name='recipient_type',
            field=models.CharField(blank=True, choices=[('STUDENT', "O'quvchi"), ('ADMIN', 'Admin'), ('TEACHER', "O'qituvchi")], max_length=20, verbose_name='Kimga yuborildi'),
        ),
        migrations.AlterField(
            model_name='telegramappeal',
            name='sender_type',
            field=models.CharField(choices=[('STUDENT', "O'quvchi"), ('ADMIN', 'Admin'), ('TEACHER', "O'qituvchi")], default='STUDENT', max_length=20, verbose_name='Xabar turi'),
        ),
    ]
