# Generated by Django 5.1.1 on 2026-06-29 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users1', '0002_add_phone_to_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('DIRECTOR', 'Director'), ('ADMINISTRATOR', 'Administrator'), ('TEACHER', "O'qituvchi")], default='TEACHER', max_length=20),
        ),
    ]
