# Generated by Django 6.0.6 on 2026-06-30 18:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups_app', '0007_group_duration_group_end_time'),
        ('users1', '0004_user_photo_auditlog_teacherpenalty'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='auditlog',
            options={'ordering': ['-created_at'], 'verbose_name': 'Audit Log', 'verbose_name_plural': 'Audit Loglar'},
        ),
        migrations.AlterModelOptions(
            name='teacherpenalty',
            options={'ordering': ['-created_at'], 'verbose_name': 'Jarima', 'verbose_name_plural': 'Jarimalar'},
        ),
        migrations.AddField(
            model_name='teacherpenalty',
            name='given_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='penalties_given', to=settings.AUTH_USER_MODEL, verbose_name='Kim berdi'),
        ),
        migrations.AddField(
            model_name='teacherpenalty',
            name='penalty_type',
            field=models.CharField(choices=[('ATTENDANCE_MISSED', 'Davomat olinmadi (darsga keldi)'), ('CLASS_SKIPPED', 'Darsga kelmadi'), ('CONSECUTIVE_MISSED', 'Ketma-ket davomat olinmadi'), ('MANUAL', "Qo'lda kiritildi")], default='ATTENDANCE_MISSED', max_length=30, verbose_name='Jarima turi'),
        ),
        migrations.AddField(
            model_name='user',
            name='is_blocked',
            field=models.BooleanField(default=False, verbose_name='Bloklangan'),
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='action',
            field=models.CharField(max_length=255, verbose_name='Amal'),
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Sana va vaqt'),
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='ip_address',
            field=models.GenericIPAddressField(blank=True, null=True, verbose_name='IP manzil'),
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='target_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs_target', to=settings.AUTH_USER_MODEL, verbose_name='Kim haqida'),
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs_created', to=settings.AUTH_USER_MODEL, verbose_name='Kim bajardi'),
        ),
        migrations.AlterField(
            model_name='teacherpenalty',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan vaqt'),
        ),
        migrations.AlterField(
            model_name='teacherpenalty',
            name='date',
            field=models.DateField(verbose_name='Dars sanasi'),
        ),
        migrations.AlterField(
            model_name='teacherpenalty',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='groups_app.group', verbose_name='Guruh'),
        ),
        migrations.AlterField(
            model_name='teacherpenalty',
            name='is_manual',
            field=models.BooleanField(default=False, verbose_name="Qo'lda berildi"),
        ),
        migrations.AlterField(
            model_name='teacherpenalty',
            name='teacher',
            field=models.ForeignKey(limit_choices_to={'role': 'TEACHER'}, on_delete=django.db.models.deletion.CASCADE, related_name='penalties', to=settings.AUTH_USER_MODEL, verbose_name="O'qituvchi"),
        ),
        migrations.CreateModel(
            name='MissedAttendanceAlert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lesson_date', models.DateField(verbose_name='Dars sanasi')),
                ('status', models.CharField(choices=[('PENDING', 'Kutilmoqda'), ('CAME', 'Keldi (davomat olinsin)'), ('NOT_CAME', 'Kelmadi (-10 ball)'), ('RESOLVED', 'Hal qilindi')], default='PENDING', max_length=20, verbose_name='Holati')),
                ('penalty_applied', models.BooleanField(default=False, verbose_name='Jarima berildi')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='groups_app.group', verbose_name='Guruh')),
                ('resolved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resolved_alerts', to=settings.AUTH_USER_MODEL, verbose_name='Kim hal qildi')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='missed_alerts', to=settings.AUTH_USER_MODEL, verbose_name="O'qituvchi")),
            ],
            options={
                'verbose_name': 'Davomat ogohlantirishi',
                'verbose_name_plural': 'Davomat ogohlantirishlari',
                'ordering': ['-created_at'],
                'unique_together': {('teacher', 'group', 'lesson_date')},
            },
        ),
    ]
