# Generated by Django 5.1.1 on 2026-07-01 17:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users1', '0005_alter_auditlog_options_alter_teacherpenalty_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='auditlog',
            name='new_data',
            field=models.JSONField(blank=True, null=True, verbose_name="Yangi ma'lumot"),
        ),
        migrations.AddField(
            model_name='auditlog',
            name='old_data',
            field=models.JSONField(blank=True, null=True, verbose_name="Eski ma'lumot"),
        ),
        migrations.AddField(
            model_name='auditlog',
            name='role',
            field=models.CharField(blank=True, default='', max_length=50, verbose_name='Rol'),
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='target_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs_target', to=settings.AUTH_USER_MODEL, verbose_name='Kim haqida'),
        ),
    ]
