# Generated by Django 6.0.6 on 2026-07-02 13:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups_app', '0007_group_duration_group_end_time'),
        ('users1', '0008_user_deleted_at_user_deleted_by_user_is_deleted'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScheduleChangeRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('old_day', models.CharField(max_length=20, verbose_name='Hozirgi dars kuni')),
                ('old_start_time', models.TimeField(verbose_name='Hozirgi boshlanish vaqti')),
                ('old_end_time', models.TimeField(verbose_name='Hozirgi tugash vaqti')),
                ('new_day', models.CharField(max_length=20, verbose_name='Yangi dars kuni')),
                ('new_start_time', models.TimeField(verbose_name='Yangi boshlanish vaqti')),
                ('new_end_time', models.TimeField(verbose_name='Yangi tugash vaqti')),
                ('reason', models.TextField(verbose_name='Sabab')),
                ('status', models.CharField(choices=[('PENDING', 'Kutilmoqda'), ('APPROVED', 'Tasdiqlandi'), ('REJECTED', 'Rad etildi'), ('CANCELLED', 'Bekor qilindi')], default='PENDING', max_length=20, verbose_name='Holati')),
                ('submitted_at', models.DateTimeField(auto_now_add=True, verbose_name='Yuborilgan sana')),
                ('reviewed_at', models.DateTimeField(blank=True, null=True, verbose_name="Ko'rib chiqilgan sana")),
                ('review_comment', models.TextField(blank=True, default='', verbose_name="Ko'rib chiqish izohi")),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='groups_app.group', verbose_name='Guruh')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='schedule_requests_reviewed', to=settings.AUTH_USER_MODEL, verbose_name="Kim ko'rib chiqdi")),
                ('teacher', models.ForeignKey(limit_choices_to={'role': 'TEACHER'}, on_delete=django.db.models.deletion.CASCADE, related_name='schedule_change_requests', to=settings.AUTH_USER_MODEL, verbose_name="O'qituvchi")),
            ],
            options={
                'verbose_name': "Jadval o'zgartirish arizasi",
                'verbose_name_plural': "Jadval o'zgartirish arizalari",
                'ordering': ['-submitted_at'],
            },
        ),
    ]
