# Generated by Django 6.0.6 on 2026-07-02 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users1', '0009_schedulechangerequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedulechangerequest',
            name='effective_week_start',
            field=models.DateField(blank=True, null=True, verbose_name='Qaysi hafta uchun amal qiladi'),
        ),
    ]
