# Generated by Django 5.1.1 on 2026-07-22 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users1', '0010_schedulechangerequest_effective_week_start'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedulechangerequest',
            name='change_date',
            field=models.DateField(blank=True, null=True, verbose_name="Qaysi sana uchun o'zgarish"),
        ),
        migrations.AddField(
            model_name='schedulechangerequest',
            name='change_type',
            field=models.CharField(choices=[('ADMIN_DIRECT', "Admin to'g'ridan-to'g'ri"), ('TEACHER_REQUEST', "O'qituvchi arizasi")], default='TEACHER_REQUEST', max_length=20, verbose_name="O'zgartirish turi"),
        ),
    ]
