# Generated by Django 6.0.8 on 2026-10-02 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users1', '0011_add_change_date_and_type_to_schedule_change_request'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='auditlog',
            index=models.Index(fields=['-created_at'], name='audit_created_idx'),
        ),
    ]
