# Generated by Django 5.1.1 on 2026-06-29 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendancesession',
            name='homework',
            field=models.TextField(blank=True, verbose_name='Uyga vazifa'),
        ),
        migrations.AddField(
            model_name='attendancesession',
            name='lesson_topic',
            field=models.CharField(blank=True, max_length=255, verbose_name='Dars mavzusi'),
        ),
    ]
