# Generated by Django 5.1.1 on 2026-07-02 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0003_lessonplan'),
    ]

    operations = [
        migrations.AddField(
            model_name='lessonplan',
            name='is_exam',
            field=models.BooleanField(default=False, verbose_name='Imtihon'),
        ),
    ]
