# Generated by Django 6.0.8 on 2026-10-02 13:27

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0004_add_is_exam_to_lessonplan'),
        ('groups_app', '0008_groupstudent_billing_dates'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='attendancesession',
            index=models.Index(fields=['date'], name='att_session_date_idx'),
        ),
    ]
